services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: egem-postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: egem_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
